### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by cumali-demir** [akveo/kittenTricks#54] opened 2018-02-16 12:46 UTC
when click the auth and click Login V1 there is a this error..

Warning: Failed prop type: Invalid props.style key `fontSize` supplied to `View`.
Bad object: {
  "flexDirection": "row",
  "borderBottomWidth": 1,
  "borderBottomColor": "#0000003B",
  "marginVertical": 9,
  "backgroundColor": "#ffffff",
  "borderRadius": 100,
  "borderWidth": 1,
  "borderColor": "#0000003B",
  "fontSize": 16.07142857142857,
  "opacity": 1
}
Valid keys: [
  "display",
  "width",
  "height",
  "start",
  "end",
  "top",
  "left",
  "right",
  "bottom",
  "minWidth",
  "maxWidth",
  "minHeight",
  "maxHeight",
  "margin",
  "marginVertical",
  "marginHorizontal",
  "marginTop",
  "marginBottom",
  "marginLeft",
  "marginRight",
  "marginStart",
  "marginEnd",
  "padding",
  "paddingVertical",
  "paddingHorizontal",
  "paddingTop",
  "paddingBottom",
  "paddingLeft",
  "paddingRight",
  "paddingStart",
  "paddingEnd",
  "borderWidth",
  "borderTopWidth",
  "borderStartWidth",
  "borderEndWidth",
  "borderRightWidth",
  "borderBottomWidth",
  "borderLeftWidth",
  "position",
  "flexDirection",
  "flexWrap",
  "justifyContent",
  "alignItems",
  "alignSelf",
  "alignContent",
  "overflow",
  "flex",
  "flexGrow",
  "flexShrink",
  "flexBasis",
  "aspectRatio",
  "zIndex",
  "direction",
  "shadowColor",
  "shadowOffset",
  "shadowOpacity",
  "shadowRadius",
  "transform",
  "transformMatrix",
  "decomposedMatrix",
  "scaleX",
  "scaleY",
  "rotation",
  "translateX",
  "translateY",
  "backfaceVisibility",
  "backgroundColor",
  "borderColor",
  "borderTopColor",
  "borderRightColor",
  "borderBottomColor",
  "borderLeftColor",
  "borderStartColor",
  "borderEndColor",
  "borderRadius",
  "borderTopLeftRadius",
  "borderTopRightRadius",
  "borderTopStartRadius",
  "borderTopEndRadius",
  "borderBottomLeftRadius",
  "borderBottomRightRadius",
  "borderBottomStartRadius",
  "borderBottomEndRadius",
  "borderStyle",
  "opacity",
  "elevation"
]
    in View (at createAnimatedComponent.js:134)
    in AnimatedComponent (at TouchableOpacity.js:245)
    in TouchableOpacity (at rkTextInput.js:184)
    in RkTextInput (at login1.js:64)
    in RCTView (at View.js:112)
    in View (at login1.js:52)
    in RCTView (at View.js:112)
    in View (at createAnimatedComponent.js:134)
    in AnimatedComponent (at rkAvoidKeyboard.js:77)
    in RkAvoidKeyboard (at login1.js:47)
    in LoginV1 (at rkThemeProvider.js:41)
    in ThemeProvider (at SceneView.js:31)
    in SceneView (at CardStack.js:412)
    in RCTView (at View.js:112)
    in View (at CardStack.js:411)
    in RCTView (at View.js:112)
    in View (at CardStack.js:410)
    in RCTView (at View.js:112)
    in View (at createAnimatedComponent.js:134)
    in AnimatedComponent (at Card.js:26)
    in Card (at PointerEventsContainer.js:55)
    in Container (at CardStack.js:454)
    in RCTView (at View.js:112)
    in View (at CardStack.js:383)
    in RCTView (at View.js:112)
    in View (at CardStack.js:382)
    in CardStack (at CardStackTransitioner.js:97)
    in RCTView (at View.js:112)
    in View (at Transitioner.js:192)
    in Transitioner (at CardStackTransitioner.js:49)
    in CardStackTransitioner (at StackNavigator.js:60)
    in Unknown (at createNavigator.js:52)
    in Navigator (at createNavigationContainer.js:212)
    in NavigationContainer (at SceneView.js:31)
    in SceneView (at DrawerScreen.js:40)
    in DrawerScreen (at withCachedChildNavigation.js:66)
    in withCachedChildNavigation(DrawerScreen) (at DrawerNavigator.js:106)
    in Unknown (at createNavigator.js:52)
    in Navigator (at DrawerView.js:215)
    in RCTView (at View.js:112)
    in View (at createAnimatedComponent.js:134)
    in AnimatedComponent (created by DrawerLayout)
    in RCTView (at View.js:112)
    in View (created by DrawerLayout)
    in DrawerLayout (at DrawerView.js:195)
    in DrawerView (at DrawerNavigator.js:127)
    in Unknown (at createNavigator.js:52)
    in Navigator (at createNavigationContainer.js:212)
    in NavigationContainer (at SceneView.js:31)
    in SceneView (at CardStack.js:423)
    in RCTView (at View.js:112)
    in View (at createAnimatedComponent.js:134)
    in AnimatedComponent (at Card.js:26)
    in Card (at PointerEventsContainer.js:55)
    in Container (at CardStack.js:454)
    in RCTView (at View.js:112)
    in View (at CardStack.js:383)
    in RCTView (at View.js:112)
    in View (at CardStack.js:382)
    in CardStack (at CardStackTransitioner.js:97)
    in RCTView (at View.js:112)
    in View (at Transitioner.js:192)
    in Transitioner (at CardStackTransitioner.js:49)
    in CardStackTransitioner (at StackNavigator.js:60)
    in Unknown (at createNavigator.js:52)
    in Navigator (at createNavigationContainer.js:212)
    in NavigationContainer (at app.js:86)
    in RCTView (at View.js:112)
    in View (at app.js:85)
    in App (at registerRootComponent.js:35)
    in RootErrorBoundary (at registerRootComponent.js:34)
    in ExpoRootComponent (at renderApplication.js:35)
    in RCTView (at View.js:112)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:112)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:34)
- node_modules/fbjs/lib/warning.js:33:20 in printWarning
- ... 19 more stack frames from framework internals

**Comment by malashkevich** [comment] 2018-02-16 13:05
Hello @cumali-demir.
It's not error. This is warning. And this is duplicate of #53

**Closed as completed by malashkevich** 2018-02-16 13:05 UTC
